### ISSUE TITLE
uuid is not saved in JSON file

### ISSUE THREAD

**Issue by ggearing** [iotexpert/memosystem#36]
The JSON file does not include the uuid of individual files:
{"title": "test 2", "number": 2, "version": "A", "confidential": false, "distribution": "", "keywords": "", "userid": "ggearing", "memo_state": "MemoState.Active", "signers": "", "references": "", "files": ["Torch.jpg"]}

**Comment by iotexpert** [comment]
Fix with js['files'].append((file.filename,file.uuid))
